export const currencyByRupee: Currency[] = [
    { name: 'US Dollar', value: 83.20, flag: '🇺🇸', symbol: '$' },
    { name: 'Euro', value: 89.50, flag: '🇪🇺', symbol: '€' },
    { name: 'British Pound', value: 104.25, flag: '🇬🇧', symbol: '£' },
    { name: 'Japanese Yen', value: 0.57, flag: '🇯🇵', symbol: '¥' },
    { name: 'Australian Dollar', value: 54.50, flag: '🇦🇺', symbol: 'A$' },
    { name: 'Canadian Dollar', value: 62.30, flag: '🇨🇦', symbol: 'C$' },
    { name: 'Swiss Franc', value: 92.10, flag: '🇨🇭', symbol: 'CHF' },
    { name: 'Chinese Yuan', value: 11.40, flag: '🇨🇳', symbol: '¥' },
    { name: 'Singapore Dollar', value: 60.90, flag: '🇸🇬', symbol: 'S$' },
    { name: 'Indian Rupee', value: 1.00, flag: '🇮🇳', symbol: '₹' },
    { name: 'South Korean Won', value: 0.071, flag: '🇰🇷', symbol: '₩' },
    { name: 'Russian Ruble', value: 1.10, flag: '🇷🇺', symbol: '₽' },
    { name: 'Brazilian Real', value: 15.30, flag: '🇧🇷', symbol: 'R$' },
    { name: 'South African Rand', value: 4.90, flag: '🇿🇦', symbol: 'R' },
    { name: 'Mexican Peso', value: 4.15, flag: '🇲🇽', symbol: 'MX$' },
    { name: 'Turkish Lira', value: 5.00, flag: '🇹🇷', symbol: '₺' },
    { name: 'Malaysian Ringgit', value: 18.70, flag: '🇲🇾', symbol: 'RM' },
    { name: 'Indonesian Rupiah', value: 0.0056, flag: '🇮🇩', symbol: 'Rp' },
    { name: 'Thai Baht', value: 2.40, flag: '🇹🇭', symbol: '฿' },
    { name: 'Philippine Peso', value: 1.50, flag: '🇵🇭', symbol: '₱' },
    { name: 'New Zealand Dollar', value: 50.60, flag: '🇳🇿', symbol: 'NZ$' },
    { name: 'Swedish Krona', value: 7.80, flag: '🇸🇪', symbol: 'kr' },
    { name: 'Norwegian Krone', value: 8.40, flag: '🇳🇴', symbol: 'kr' },
    { name: 'Danish Krone', value: 12.00, flag: '🇩🇰', symbol: 'kr' },
    { name: 'Saudi Riyal', value: 22.20, flag: '🇸🇦', symbol: 'SAR' },
];